--- # Create File and Add the line to the File
-  hosts: centos
   tasks: 
   - name: create a file if does not exist
     file:
         state: touch
         path: /home/ansible/hostname.conf
   - name: If line not there then add it
     lineinfile:
            state: present
            dest: /home/ansible/hostname.conf
            line: Hostname={{ ansible_hostname}}